spring:
  application:
    name: runnerz
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: runnerz
    url: jdbc:postgresql://localhost:5432/runnerz
    username: theoddagen
    password: password
  sql:
    init:
      mode: always


server:
  error:
    include-stacktrace: never
  port: 8085